// This module implements the HYBRID pipeline with REAL AI (Gemini)
import { GoogleGenerativeAI } from '@google/generative-ai';
import dotenv from 'dotenv';

dotenv.config();

// Initialize Gemini
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

// 1. DETERMINISTIC FUNCTIONS (Rule-based)
export function extractDependencies(content: string): string[] {
  // In a real app, this would parse package.json content
  // For this v1, we'll keep the mock list but acknowledging it's a placeholder for file parsing
  const deps = ['react', 'typescript', 'express', 'tailwindcss', '@google/generative-ai'];
  return deps.sort();
}

export function validateStructure(files: string[]): { isValid: boolean; issues: string[] } {
  const issues: string[] = [];
  if (!files.includes('package.json')) issues.push('Missing package.json');
  if (!files.includes('README.md')) issues.push('Missing README.md');
  
  return {
    isValid: issues.length === 0,
    issues
  };
}

// 2. REAL AI FUNCTION (Calls Google Gemini)
export async function assessWithAI(codeSnippet: string): Promise<{
  complexity: 'low' | 'medium' | 'high';
  suggestions: string[];
  confidence: number;
}> {
  if (!process.env.GEMINI_API_KEY) {
    console.warn('GEMINI_API_KEY not found. Falling back to mock response.');
    return {
      complexity: 'low',
      suggestions: ['Configure GEMINI_API_KEY to get real insights'],
      confidence: 0.0
    };
  }

  try {
    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-pro' });

    const prompt = `
      Analyze the following code snippet for architectural quality, complexity, and potential improvements.
      Return ONLY a JSON object with this strict schema (no markdown formatting):
      {
        "complexity": "low" | "medium" | "high",
        "suggestions": ["string", "string"],
        "confidence": number (0.0 to 1.0)
      }

      Code to analyze:
      ${codeSnippet.substring(0, 2000)} // Truncate for safety
    `;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();
    
    // Clean up markdown block if present
    const jsonStr = text.replace(/```json\n?|\n?```/g, '').trim();
    return JSON.parse(jsonStr);
  } catch (error) {
    console.error('Gemini API Error:', error);
    return {
      complexity: 'high',
      suggestions: ['AI Analysis failed - check logs'],
      confidence: 0.0
    };
  }
}

// 3. MAIN HYBRID PIPELINE
export async function analyzeRepository(repoUrl: string): Promise<any> {
  console.log(`Starting hybrid analysis for: ${repoUrl}`);
  
  // DETERMINISTIC STEP 1: Validate input
  if (!repoUrl.includes('github.com')) {
    throw new Error('Only GitHub repositories are supported');
  }
  
  // DETERMINISTIC STEP 2: Simulate fetching repo structure
  // In production, this would use the GitHub API to list real files
  const simulatedFiles = ['package.json', 'src/index.ts', 'README.md', '.github/workflows/test.yml'];
  
  // DETERMINISTIC STEP 3: Rule-based validation
  const structureReport = validateStructure(simulatedFiles);
  
  // AI STEP: Real AI analysis on a sample snippet
  // In production, we would fetch the actual 'critical file' content
  const sampleCode = `
    function complexOperation(data) {
      // This is a sample function being sent to Gemini for analysis
      const result = data.map(item => {
        return { ...item, processed: true };
      }).filter(item => item.active);
      return result;
    }
  `;
  
  const aiReport = await assessWithAI(sampleCode);
  
  // DETERMINISTIC STEP 4: Compile final report
  return {
    repository: repoUrl,
    timestamp: new Date().toISOString(),
    deterministic_findings: {
      files_found: simulatedFiles.length,
      structure_validation: structureReport,
      dependencies: extractDependencies('simulated')
    },
    ai_insights: {
      ...aiReport,
      provider: 'Google Gemini 1.5 Pro',
      disclaimer: 'AI insights generated by Gemini'
    },
    overall_risk_score: structureReport.isValid ? 0.2 : 0.7,
    recommendations: [
      structureReport.isValid ? '✅ Repository structure looks good' : '⚠️ Add missing configuration files',
      ...aiReport.suggestions,
      '📊 Monitor dependency updates'
    ]
  };
}
